/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Stitch WinUI 3 Fluent Semantic Tokens (backed by CSS variables)
        surface: 'var(--surface)',
        'surface-dim': 'var(--surface-dim)',
        'surface-bright': 'var(--surface-bright)',
        'surface-container-lowest': 'var(--surface-container-lowest)',
        'surface-container-low': 'var(--surface-container-low)',
        'surface-container': 'var(--surface-container)',
        'surface-container-high': 'var(--surface-container-high)',
        'surface-container-highest': 'var(--surface-container-highest)',
        'on-surface': 'var(--on-surface)',
        'on-surface-variant': 'var(--on-surface-variant)',
        outline: 'var(--outline)',
        'outline-variant': 'var(--outline-variant)',
        primary: 'var(--primary)',
        'primary-container': 'var(--primary-container)',
        'on-primary': 'var(--on-primary)',
        'on-primary-container': 'var(--on-primary-container)',
        secondary: 'var(--secondary)',
        'secondary-container': 'var(--secondary-container)',
        'on-secondary': 'var(--on-secondary)',
        'on-secondary-container': 'var(--on-secondary-container)',
        background: 'var(--background)',
        'on-background': 'var(--on-background)',
        error: 'var(--error)',
        'error-container': 'var(--error-container)',

        // Adwaita legacy fallback
        adwaita: {
          bg: '#f0f0f0',
          canvas: '#9a9996',
          header: '#ebebeb',
          sidebar: '#ffffff',
          border: '#cdcdcd',
          hover: '#e0e0e0',
          active: '#d5d5d5',
          fab: '#3d3d3d',
          accent: '#0078d4',
          text: '#2e3436',
          'text-dim': '#77767b',
        },
        dark: {
          bg: '#131313',
          canvas: '#191919',
          header: '#1b1c1c',
          sidebar: '#1b1c1c',
          popover: '#202020',
          border: '#2a2a2a',
          hover: '#2a2a2a',
          active: '#353535',
          fab: '#2a2a2a',
          accent: '#0078d4',
          text: '#e5e2e1',
          'text-dim': '#c0c7d4',
        }
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-lg': '1rem',
        'space-xl': '1.5rem',
        gutter: '0.75rem',
      },
      borderRadius: {
        window: '10px',
        pill: '100px',
        xs: '2px',
        sm: '4px',
        md: '6px',
        lg: '8px',
        xl: '12px',
      },
      fontFamily: {
        sans: ['Geist', 'Segoe UI Variable', 'Segoe UI', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
        body: ['Geist', 'Segoe UI Variable', 'Segoe UI', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
      }
    },
  },
  plugins: [],
}
